# Generated by Django 3.1.5 on 2021-01-24 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=10)),
                ('event', models.CharField(max_length=40)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
