# Generated by Django 3.1.5 on 2021-01-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0002_auto_20210127_0843'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('club', 'date', 'time'), name='unique session'),
        ),
    ]
