# Generated by Django 3.1.5 on 2021-01-26 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0003_auto_20210127_0914'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='session',
            name='unique session',
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.UniqueConstraint(fields=('club', 'date', 'time', 'event'), name='unique session'),
        ),
    ]
