# Generated by Django 3.1.5 on 2021-01-26 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0004_auto_20210127_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time',
            field=models.CharField(choices=[('M', 'Morning'), ('A', 'Afternoon'), ('E', 'Evening')], default='E', max_length=1),
        ),
    ]
