# Generated by Django 3.1.5 on 2021-01-26 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.CharField(max_length=2)),
                ('number', models.IntegerField()),
                ('player_a', models.CharField(max_length=25)),
                ('player_b', models.CharField(max_length=25)),
                ('points', models.IntegerField()),
            ],
            options={
                'ordering': ['-orientation', '-points'],
            },
        ),
    ]
