# Generated by Django 3.1.5 on 2021-01-26 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almanac', '0002_auto_20210127_0843'),
        ('pairs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pair',
            name='session',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='almanac.session'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pair',
            name='orientation',
            field=models.CharField(choices=[('NS', 'North/South'), ('EW', 'East/West')], max_length=2),
        ),
    ]
