# Generated by Django 3.1.5 on 2021-01-27 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pairs', '0004_auto_20210127_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pair',
            name='orientation',
            field=models.CharField(choices=[('NS', 'North/South'), ('EW', 'East/West')], default='NS', max_length=2),
        ),
        migrations.AlterField(
            model_name='pair',
            name='points',
            field=models.FloatField(),
        ),
    ]
